"""Browser tools using a persistent Playwright Chromium session."""

from openhands.tools.browser_use.definition import (
    BrowserClickAction,
    BrowserClickTool,
    BrowserCloseTabAction,
    BrowserCloseTabTool,
    BrowserFillFormAction,
    BrowserFillFormTool,
    BrowserFormField,
    BrowserGetContentAction,
    BrowserGetContentTool,
    BrowserGetSecretAction,
    BrowserGetSecretTool,
    BrowserGetStateAction,
    BrowserGetStateTool,
    BrowserGetStorageAction,
    BrowserGetStorageTool,
    BrowserGoBackAction,
    BrowserGoBackTool,
    BrowserListTabsAction,
    BrowserListTabsTool,
    BrowserNavigateAction,
    BrowserNavigateTool,
    BrowserObservation,
    BrowserScrollAction,
    BrowserScrollTool,
    BrowserSetStorageAction,
    BrowserSetStorageTool,
    BrowserSetViewportAction,
    BrowserSetViewportTool,
    BrowserSwitchTabAction,
    BrowserSwitchTabTool,
    BrowserToolSet,
    BrowserTypeAction,
    BrowserTypeTool,
)


__all__ = [
    # Tool classes
    "BrowserNavigateTool",
    "BrowserClickTool",
    "BrowserTypeTool",
    "BrowserFillFormTool",
    "BrowserGetStateTool",
    "BrowserGetContentTool",
    "BrowserGetSecretTool",
    "BrowserScrollTool",
    "BrowserSetViewportAction",
    "BrowserSetViewportTool",
    "BrowserGoBackTool",
    "BrowserListTabsTool",
    "BrowserSwitchTabTool",
    "BrowserCloseTabTool",
    "BrowserGetStorageTool",
    "BrowserSetStorageTool",
    # Actions
    "BrowserNavigateAction",
    "BrowserClickAction",
    "BrowserTypeAction",
    "BrowserFillFormAction",
    "BrowserFormField",
    "BrowserGetStateAction",
    "BrowserGetContentAction",
    "BrowserGetSecretAction",
    "BrowserScrollAction",
    "BrowserGoBackAction",
    "BrowserListTabsAction",
    "BrowserSwitchTabAction",
    "BrowserCloseTabAction",
    "BrowserGetStorageAction",
    "BrowserSetStorageAction",
    # Observations
    "BrowserObservation",
    "BrowserToolSet",
]
